version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/GUI"
    schedule:
      time: "00:00"
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "dev"
    versioning-strategy: "increase"
