declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'DELETE-SETTINGS'"
  method: post
  accepts: json
  returns: json
  namespace: analytics

deleteOdpKey:
  call: http.post
  args:
    url: "[#ANALYTICS_RESQL]/delete-odp-settings"
  result: delete

return:
  return: ${true}
