-- SELECT * FROM chat  
-- JOIN customer_support_agent_activity AS csa ON chat.csa_id = csa.csa_id
-- WHERE created BETWEEN :start::timestamptz AND :end::timestamptz
-- AND exists (
--     SELECT 1
--     FROM message
--     WHERE message.chat_base_id = chat.base_id
--     AND message.event = 'contact-information-fulfilled'
-- )
-- AND csa.status = 'away'
