declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'SETTINGS'"
  method: get
  accepts: json
  returns: json
  namespace: analytics

checkOdpKey:
  call: http.post
  args:
    url: "[#ANALYTICS_RESQL]/get-odp-settings"
  result: odpsettings

return:
  return: ${odpsettings.response.body[0]}

